name: "Release"

on:
  push:
    branches:
      - main

jobs:
  node:
    uses: timada-org/.github/.github/workflows/node-release.yml@v1.1.1
    with:
      filters: --filter aria --filter stately --filter types --filter components
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
